// Vuejs/vue30컴포넌트실습/comprj01/src/components/todo/TodoFooter.vue
<style scoped>
.clearAllContainer {
  width: 8.5rem;
  height: 50px;
  line-height: 50px;
  background-color: white;
  border-radius: 5px;
  margin: 0 auto;
}
.clearAllBtn {
  color: #e20303;
  display: block;
}
</style>

<template>
  <div class="clearAllContainer">
    <span class="clearAllBtn" v-on:click="clearAll">Clear All</span>
  </div>
</template>

<script>
// vuex 라이브러리에서 mapActions, mapMutations, mapState, mapGetters 함를 가져옵니다.
// import { mapActions, mapMutations, mapState, mapGetters } from 'vuex';

export default {
  //template: ``,
  methods: {
    /* 이벤트 핸들러 등록 + 일반 함수 */
    clearAll(e) {
      console.log(e.target);
      //이벤트 발생
      this.$emit('clearAll');
    },
  },
};
</script>

// React/rt20.create-reate-project/reactprj01/src/containers/todo/components/TodoFooter.js
import React from 'react';
import PropTypes from 'prop-types';
import styled, { css } from 'styled-components';

const StyledTodoFooter = styled.div`
  /* styled 설정. https://styled-components.com/docs/basics#adapting-based-on-props */
  .clearAllContainer {
    width: 16rem;
    height: 50px;
    line-height: 50px;
    background-color: white;
    border-radius: 5px;
    margin: 0 auto;
  }

  .clearAllBtn {
    color: #e20303;
    display: block;
  }
`;

function TodoFooter({ callbackClearAll }) {
  // 이벤트 핸들러 작성.
  const handlerClearAll = (e) => {
    // 이벤트 핸들러는 화살표 함수로 만든다
    console.log(e.target);
    // 부모 컴포넌트의 콜백 메서드 callbackClearAll 호출.
    callbackClearAll();
  };

  // JSX로 화면 만들기. 조건부 렌더링: https://ko.reactjs.org/docs/conditional-rendering.html
  return (
    <StyledTodoFooter>
      <div className="clearAllContainer">
        <span className="clearAllBtn" onClick={handlerClearAll}>
          Clear All
        </span>
      </div>
    </StyledTodoFooter>
  );
}

TodoFooter.propTypes = {
  // props의 프로퍼티 타입 설정. https://ko.reactjs.org/docs/typechecking-with-proptypes.html
  // 인자명: PropTypes.func.isRequired,
  // 인자명: PropTypes.arrayOf(PropTypes.object),
  callbackClearAll: PropTypes.func.isRequired,
};
TodoFooter.defaultProps = {
  // props의 디폴트 값 설정. https://ko.reactjs.org/docs/typechecking-with-proptypes.html
  // 인자명: () => {},
  // 인자명: [],
  callbackClearAll: () => {},
};

export default React.memo(TodoFooter); // React.memo()는 props 미변경시 컴포넌트 리렌더링 방지 설정
